
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Oct 25 2025 10:47:08 IST (Oct 25 2025 05:17:08 UTC)

// Verification Directory fv/carry_save_adder 

module carry_save_adder(a, b, c, sum, carry);
  input [15:0] a, b, c;
  output [15:0] sum, carry;
  wire [15:0] a, b, c;
  wire [15:0] sum, carry;
  ADDFXL g1261__2398(.A (a[15]), .B (b[15]), .CI (c[15]), .CO
       (carry[15]), .S (sum[15]));
  ADDFXL g1265__5107(.A (a[0]), .B (b[0]), .CI (c[0]), .CO (carry[0]),
       .S (sum[0]));
  ADDFXL g1276__6260(.A (a[1]), .B (b[1]), .CI (c[1]), .CO (carry[1]),
       .S (sum[1]));
  ADDFXL g1275__4319(.A (a[2]), .B (b[2]), .CI (c[2]), .CO (carry[2]),
       .S (sum[2]));
  ADDFXL g1273__8428(.A (a[3]), .B (b[3]), .CI (c[3]), .CO (carry[3]),
       .S (sum[3]));
  ADDFXL g1272__5526(.A (a[4]), .B (b[4]), .CI (c[4]), .CO (carry[4]),
       .S (sum[4]));
  ADDFXL g1269__6783(.A (a[5]), .B (b[5]), .CI (c[5]), .CO (carry[5]),
       .S (sum[5]));
  ADDFXL g1268__3680(.A (a[6]), .B (b[6]), .CI (c[6]), .CO (carry[6]),
       .S (sum[6]));
  ADDFXL g1266__1617(.A (a[7]), .B (b[7]), .CI (c[7]), .CO (carry[7]),
       .S (sum[7]));
  ADDFXL g1264__2802(.A (a[8]), .B (b[8]), .CI (c[8]), .CO (carry[8]),
       .S (sum[8]));
  ADDFXL g1274__1705(.A (a[9]), .B (b[9]), .CI (c[9]), .CO (carry[9]),
       .S (sum[9]));
  ADDFXL g1271__5122(.A (a[10]), .B (b[10]), .CI (c[10]), .CO
       (carry[10]), .S (sum[10]));
  ADDFXL g1267__8246(.A (a[11]), .B (b[11]), .CI (c[11]), .CO
       (carry[11]), .S (sum[11]));
  ADDFXL g1263__7098(.A (a[12]), .B (b[12]), .CI (c[12]), .CO
       (carry[12]), .S (sum[12]));
  ADDFXL g1270__6131(.A (a[13]), .B (b[13]), .CI (c[13]), .CO
       (carry[13]), .S (sum[13]));
  ADDFXL g1262__1881(.A (a[14]), .B (b[14]), .CI (c[14]), .CO
       (carry[14]), .S (sum[14]));
endmodule

